### ISSUE TITLE
在直接跑您的代码后发现效果远超论文中记录的结果，请问这个是出现了什么问题呢

### ISSUE THREAD

**Issue by XiaoLongtaoo** [yewzz/EAGER#3]
我在通过Sentence-T5提取item的title embedding后，再运行train_rec.py发现得到的结果如下所示（所使用的是Beauty数据集，已经得到了预训练的DIN模型）：![result](https://github.com/user-attachments/assets/7b0723cd-043b-4efb-94e6-96ce3ff9abd0)，请问是否在计算指标的时候开源的代码与您实际使用的代码不同。期待您的回复

**Comment by yewzz** [comment]
hello～图里的结果确实有些异常，看起来似乎数据泄漏了。推测主要原因应该是数据处理部分出现了问题，供你参考：
1. 数据预处理部分。可以在完成数据预处理后，打印一下item数量等信息，看看是否与论文上的数据集信息一致。注意这里是使用了5-core的推荐数据以及leave-one-out的evaluation strategy。
2. 指标计算部分。这部分应该是与RecForest仓库中提供的代码一致的，可以对照看看～。

**Comment by XiaoLongtaoo** [comment]
![result](https://github.com/user-attachments/assets/e47099b5-a0f3-4117-a555-5a7e386813c2)
请问是这个All_Beauty 5-core的数据集吗？这个处理之后的结果与论文中的明显不一样

**Comment by XiaoLongtaoo** [comment]
> ![result](https://private-user-images.githubusercontent.com/90383205/366004741-e47099b5-a0f3-4117-a555-5a7e386813c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjkwODMsIm5iZiI6MTcyNjAyODc4MywicGF0aCI6Ii85MDM4MzIwNS8zNjYwMDQ3NDEtZTQ3MDk5YjUtYTBmMy00MTE3LWE1NTUtNWE3ZTM4NjgxM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA0MjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MDZlMDAxM2JjODYwNmQwMDM2Y2JkNjA4OGE2YWQ2NzA4NzBkMWJhMGJjMjBhYTA1Yzk1YTdhNmNjODcwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U6QYkPMgTDzPF3NRlcjb9v-vS7Eo4Chi2_PXdAlDVjo) 请问是这个All_Beauty 5-core的数据集吗？这个处理之后的结果与论文中的明显不一样

此处已解决，经过调查发现，您所使用的并不是18数据集，应该是14的数据集，这样生成的item_num与user_num与论文才保持一致

**Comment by zhaijianyang** [comment]
你好，请问你复现出来结果了吗？为什么我跑出来结果低好多，而且是直接用测试集来验证？

**Comment by zhaijianyang** [comment]
你好，请问你复现出了Beauty数据集的结果吗？
